python/l3ms/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from settings import URL_PREFIX, DEBUG, PROJECT_ROOT
import accounts.urls
import accounts.views
import email_validation.views
import http_auth.urls
import courses.urls
import gradebook.urls

admin.autodiscover()

subpatterns = patterns(
    '',
    url(r'^$', accounts.views.home, name='home'),
    url(r'^u/(?P<username>\w+)$', accounts.views.profile, name='profile'),
    url(r'^u/$', accounts.views.all_users, name='all_users'),
    url(r'^v/(?P<key>.+)$', email_validation.views.validate,
        name='validate'),
    url(r'^nav/(?P<path>.+)$', courses.views.nav, name='nav'),
    url(r'about$', accounts.views.about, name='about'),
    (r'^acct/', include(accounts.urls)),
    (r'^auth/', include(http_auth.urls)),
    (r'^admin/', include(admin.site.urls)),
    (r'^course/', include(courses.urls)),
    (r'^grades/', include(gradebook.urls)),
    )

if DEBUG:
    subpatterns += patterns(
        '',
        url(r'^test/valid/(?P<code>\w)(?P<user>\d+)/(?P<email>.+)$',
            email_validation.views.test, name='test_validation'),
        )

urlpatterns = patterns(
    '',
    (r'^'+URL_PREFIX, include(subpatterns))
    )

if DEBUG:
    from django.views.static import serve
    from os.path import join

    urlpatterns += patterns(
        '',
        (r'^l3media/(?P<path>.*)$', serve,
         {'document_root': join(PROJECT_ROOT, 'static')})
        )

python/l3ms/accounts/forms.py
# l3ms.accounts.forms    -*- coding: utf-8 -*-
# Copyright ©2011 by Christopher League <league@contrapunctus.net>
#
# This is free software but comes with ABSOLUTELY NO WARRANTY.
# See the GNU General Public License version 3 for details.

from django import forms
from django.conf import settings
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.template import loader, Context
from models import UserProfile
from strings import *

class EmailBaseForm(forms.Form):
    email = forms.EmailField(label=LABEL_EMAIL, max_length=75)

class RetrieveUsernameForm(EmailBaseForm):
    def clean_email(self):
        email = self.cleaned_data["email"]
        try:
            self.user = User.objects.get(email=email)
            return email
        except User.DoesNotExist:
            raise forms.ValidationError(M_EMAIL_UNKNOWN)

class ResetPasswordForm(forms.Form):
    username = forms.CharField(label=LABEL_USERNAME, max_length=30)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            self.user = User.objects.get(username=username)
            return username
        except User.DoesNotExist:
            raise forms.ValidationError(M_USERNAME_UNKNOWN)

class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set his/her password without
    entering the old password
    """
    new_password1 = forms.CharField(label=LABEL_PASSWORD_1,
                                    widget=forms.PasswordInput)
    new_password2 = forms.CharField(label=LABEL_PASSWORD_2,
                                    widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(M_PASSWORDS_NEQ)
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user

class EditProfileForm(forms.Form):
    last_name = forms.CharField(label=LABEL_LAST_NAME, max_length=30)
    first_name = forms.CharField(label=LABEL_FIRST_NAME, max_length=30)
    blurb = forms.CharField(label=LABEL_BLURB, widget=forms.Textarea,
                            required=False)

    def __init__(self, user, data=None, *args, **kwargs):
        self.user = user
        if not data:
            data = {}
        if 'first_name' not in data:
            data['first_name'] = user.first_name
        if 'last_name' not in data:
            data['last_name'] = user.last_name
        if 'blurb' not in data:
            data['blurb'] = user.get_profile().blurb
        super(EditProfileForm, self).__init__(data, *args, **kwargs)

    def save(self, commit=True):
        self.user.first_name = self.cleaned_data['first_name']
        self.user.last_name = self.cleaned_data['last_name']
        self.user.get_profile().blurb = self.cleaned_data['blurb']
        if commit:
            self.user.save()
            self.user.get_profile().save()
        return self.user

class RegistrationForm(forms.Form):
    last_name = forms.CharField(label=LABEL_LAST_NAME, max_length=30)
    first_name = forms.CharField(label=LABEL_FIRST_NAME, max_length=30)
    email = forms.EmailField(label=LABEL_EMAIL)
    username = forms.RegexField(label=LABEL_USERNAME, max_length=30,
                                regex=r'^\w+$')
    password1 = forms.CharField(label=LABEL_PASSWORD_1, max_length=128,
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label=LABEL_PASSWORD_2, max_length=128,
                                widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(M_USERNAME_IN_USE)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(M_PASSWORDS_NEQ)
        return password2

    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            User.objects.get(email=email)
            raise forms.ValidationError(M_EMAIL_IN_USE)
        except User.DoesNotExist:
            return email

    def save(self):
        self.user = User.objects.create_user(self.cleaned_data['username'],
                                             self.cleaned_data['email'],
                                             self.cleaned_data['password1'])
        self.user.first_name = self.cleaned_data['first_name']
        self.user.last_name = self.cleaned_data['last_name']
        self.user.is_active = False
        self.user.save()
        return self.user

templates/acct/about.html
{% extends "http-auth/narrow.html" %}
{% block small_content %}
<h1>About this site</h1>

<p><b>l3ms</b> is a lightweight learning management system.  It
  provides a gradebook, account management, and authentication for
  static pages and software repositories.  It was developed by
  by <a href="http://contrapunctus.net/">Christopher League</a> using
  Python and the Django web framework.  The source is available
  on <a href="http://github.com/league/">github</a>.
</p>
<p>
  <b>liucs.net</b> hosts several courses and other resources from the
  Computer Science department at Long Island University's Brooklyn
  Campus.
</p>
<p>
  This program is <b>free software:</b> you can redistribute it and/or
    modify it under the terms of the GNU General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.  This program is
    distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
    License for more details.
</p>
{{block.super}}
{% endblock %}

templates/acct/all.html
{% extends "layout/base.html" %}
{% load gravatar %}
{% block title %}
{{ site_name }} users
{% endblock title %}

{% block content %}
{% for u in users %}
{% cycle '<div class="container_12 clearfix allusers">' '' '' '' %}
  <div class="grid_1 {% cycle 'alpha' '' '' '' %}">
    <a href="{% url profile username=u.username %}">
      <img class="gravatar" src="{{ u|gravatar:60 }}"
           width="60" height="60" />
    </a>
  </div>
  <div class="grid_2 {% cycle '' '' '' 'omega' %}">
    <a href="{% url profile username=u.username %}">
      {{ u.username }}<br />
      {{ u.get_full_name }}
    </a>
  </div>
  {% cycle '' '' '' '</div>' %}
{% endfor %}
{% endblock %}

templates/acct/edit-email.html
{% extends "acct/narrow.html" %}
{% block title %}
  Change email for {{ profile.username }} | {{ site_name }}
{% endblock %}

{% block small_content %}
<h1>Change email for
  {{ profile.get_full_name|default:profile.username }}</h1>

<p>Enter your new email address below.  You will receive a validation
  link at that address.  You must click that link to effect the
  change.  If you uploaded a ‘gravatar’, it was based on your email
  address, so you may have to upload a new one after.</p>

<form class="simpleForm" method="post" action="{{ action }}">
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

{{ block.super }}
{% endblock %}

templates/acct/edit-password.html
{% extends "acct/narrow.html" %}
{% block title %}
  Change password for {{ profile.username }} | {{ site_name }}
{% endblock %}

{% block small_content %}
<h1>Change password for
  {{ profile.get_full_name|default:profile.username }}</h1>

<form class="simpleForm" method="post" action="{{action}}">
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

{{ block.super }}
{% endblock %}

templates/acct/edit-profile.html
{% extends "acct/narrow.html" %}
{% block title %}
  Change profile info for {{ profile.username }} | {{ site_name }}
{% endblock %}

{% block small_content %}
<h1>Change profile info for
  {{ profile.get_full_name|default:profile.username }}</h1>

<p>Edit your information below.  If you are an enrolled student,
  please use the last name that is on the university roster.  You may
  supplement the first name with a nickname, as long as it is obvious
  who you are.  Also please tell us a bit about yourself: your
  background, interests, motivations, etc.</p>

<form class="simpleForm" method="post" action="{{action}}">
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

{{ block.super }}
{% endblock %}

templates/acct/narrow.html
{% extends "layout/narrow.html" %}
{% block small_content %}
<p class="links">
  <a href="{% url profile username=profile.username %}">
    ←  Back to profile
  </a>
</p>
{% endblock %}

templates/acct/register.html
{% extends "http-auth/narrow.html" %}

{% block title %}
Sign up for {{ site_name }}
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript">
var auto_type_username = true
var username_okay_cache = {}
$(document).ready(function(){
  $("#id_username").after("<span id='feedback_username' class='feedback okay'></span>")
  $("#id_email").after("<span id='feedback_email' class='feedback'></span>")
  $("#id_password2").after("<span id='feedback_password2' class='feedback'>&nbsp;</span>")
  $("#id_first_name").keyup(realNameHandler)
  $("#id_last_name").keyup(realNameHandler)
  $("#id_username").keyup(userNameHandler)
  $("#id_email").focusout(emailHandler)
  $("#id_password2").keyup(passwordHandler)
})
function realNameHandler() {
  if(auto_type_username) {
    var fn = $("#id_first_name").val()
    var ln = $("#id_last_name").val()
    if(fn != "" && ln != "") {
      $("#id_username").val((ln+fn[0]).toLowerCase().replace(/[^a-z]/, ""))
      userNameCheck()
    }
  }
}
function userNameHandler() {
  auto_type_username = false
  userNameCheck()
}
function userNameCheck() {
  u = $("#id_username").val()
  if( u.length > 0 ) {
    if( u in username_okay_cache ) {
      showUsernameFeedback({available: true})
    }
    else {
      $.getJSON("{% url check_username %}",
                {u: $("#id_username").val(),
                 f: $("#id_first_name").val(),
                 l: $("#id_last_name").val()},
                function(result) {
                  if(result.available) username_okay_cache[u] = true
                  showUsernameFeedback(result)
                })
    }
  }
  else {
    $("#feedback_username").removeClass("error").removeClass("okay").
      html("&nbsp;")
  }
}
function showUsernameFeedback(result) {
  if(result.available) {
    $("#feedback_username").removeClass("error").addClass("okay").
      html("&nbsp;")
  }
  else {
    $("#feedback_username").removeClass("okay").addClass("error").
      text("That username is taken. Suggestions:" +
           result.suggestions.join(" "))
  }
}
function emailHandler() {
  $.getJSON("{% url check_email %}",
            {e: $("#id_email").val()},
            function(result) {
              if(!result.valid) {
                $("#feedback_email").removeClass("okay").addClass("error").
                  html("That is not a valid email address.")
              }
              else if(!result.available) {
                $("#feedback_email").removeClass("okay").addClass("error").
                  html("That email address is used by another account.")
              }
              else {
                $("#feedback_email").removeClass("error").addClass("okay").
                  html("&nbsp;")
              }
            })
}
function passwordHandler() {
  var p1 = $("#id_password1").val()
  var p2 = $("#id_password2").val()
  if( p1.length > 0 && p2.length > 0 && p1 == p2 ) {
    $("#feedback_password2").removeClass("error").addClass("okay")
  }
  else {
    $("#feedback_password2").removeClass("okay").addClass("error")
  }
}

</script>
{% endblock %}


{% block small_content %}
<h1>Sign up</h1>

<p>Please enter your details below.  All fields are required.  After
  submitting, you will need to follow the validation link sent to your
  email address before you can log in.</p>

<form class="simpleForm" method="post" action="{{action}}">
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

{{ block.super }}
{% endblock %}

templates/acct/reset.html
{% extends "http-auth/narrow.html" %}

{% block title %}
Reset {{ site_name }} password
{% endblock %}

{% block small_content %}
<h1>Reset password</h1>

<p>Enter your user name.  We will send a link to your email address
  that, when followed, will permit you to set a new password for your
  account.</p>

<form id="forgot_password" class="simpleForm" method="post"
      action="{% url forgot_password %}">
  {{ form.as_p }}
  <input class="submit" type="submit" value="Submit" />
</form>

{{ block.super }}
{% endblock %}

templates/acct/reset2.html
{% extends "http-auth/narrow.html" %}

{% block title %}
Reset {{ site_name }} password
{% endblock %}

{% block small_content %}
<h1>Reset password</h1>

<p>To reset the password for your account, type it twice below.</p>

<form class="simpleForm" method="post" action="{{ url }}">
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

{{ block.super }}
{% endblock %}

templates/acct/retrieve.html
{% extends "http-auth/narrow.html" %}

{% block title %}
Retrieve {{ site_name }} user name
{% endblock %}

{% block small_content %}
    <h1>Retrieve user name</h1>

    <p>To retrieve your user name, please provide the email address on
      your account.</p>

    <form id="forgot_username" class="simpleForm" method="post"
          action="{% url forgot_username %}">
      {{ form.as_p }}
      <input class="submit" type="submit" value="Submit" />
    </form>

    {{ block.super }}
{% endblock %}