python/l3ms/courses/urls.py
from django.conf import settings
from django.conf.urls.defaults import *
import views

urlpatterns = patterns(
    '',
    url(r'^$', views.all_courses, name='all_courses'),
    url(r'^(?P<tag>\w+)/$', views.one_course, name='one_course'),
    url(r'^(?P<tag>\w+)/emails$', views.mass_email, name='mass_email'),
    )

python/l3ms/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from settings import URL_PREFIX, DEBUG, PROJECT_ROOT
import accounts.urls
import accounts.views
import email_validation.views
import http_auth.urls
import courses.urls
import gradebook.urls

admin.autodiscover()

subpatterns = patterns(
    '',
    url(r'^$', accounts.views.home, name='home'),
    url(r'^u/(?P<username>\w+)$', accounts.views.profile, name='profile'),
    url(r'^u/$', accounts.views.all_users, name='all_users'),
    url(r'^v/(?P<key>.+)$', email_validation.views.validate,
        name='validate'),
    url(r'^nav/(?P<path>.+)$', courses.views.nav, name='nav'),
    url(r'about$', accounts.views.about, name='about'),
    (r'^acct/', include(accounts.urls)),
    (r'^auth/', include(http_auth.urls)),
    (r'^admin/', include(admin.site.urls)),
    (r'^course/', include(courses.urls)),
    (r'^grades/', include(gradebook.urls)),
    )

if DEBUG:
    subpatterns += patterns(
        '',
        url(r'^test/valid/(?P<code>\w)(?P<user>\d+)/(?P<email>.+)$',
            email_validation.views.test, name='test_validation'),
        )

urlpatterns = patterns(
    '',
    (r'^'+URL_PREFIX, include(subpatterns))
    )

if DEBUG:
    from django.views.static import serve
    from os.path import join

    urlpatterns += patterns(
        '',
        (r'^l3media/(?P<path>.*)$', serve,
         {'document_root': join(PROJECT_ROOT, 'static')})
        )

python/l3ms/courses/models.py
# l3ms.courses.models    -*- coding: utf-8 -*-
# Copyright ©2011 by Christopher League <league@contrapunctus.net>
#
# This is free software but comes with ABSOLUTELY NO WARRANTY.
# See the GNU General Public License version 3 for details.

from django.db import models
from django.contrib.auth.models import User, Group
from urlparse import urlsplit

class Semester(models.Model):
    tag = models.SlugField(primary_key=True)
    name = models.CharField(max_length=32, unique=True)
    start_date = models.DateField()
    end_date = models.DateField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['-end_date']

class Course(models.Model):
    tag = models.SlugField(primary_key=True)
    name = models.CharField(max_length=72)
    code = models.CharField(max_length=14)
    semester = models.ForeignKey(Semester)
    group = models.OneToOneField(Group)
    key = models.CharField(max_length=32)
    is_active = models.BooleanField()

    def __unicode__(self):
        return self.tag

    def get_users_by_kind(self, kind, incl=True):
        q = self.enrollment_set
        q = q.filter if incl else q.exclude
        q = q(kind=kind)
        q = q.order_by('user__username')
        return q

    def get_instructors(self):
        return self.get_users_by_kind('I')

    def get_students(self):
        return self.get_users_by_kind('I', False)

    def get_graded_students(self):
        return self.get_users_by_kind('G')

    def get_auditing_students(self):
        return self.get_users_by_kind('A')

    def get_full_instructor_names(self):
        return [e.user.get_full_name().replace(' ', '&nbsp;')
                for e in self.get_instructors()]

    class Meta:
        unique_together = ('semester', 'code')
        ordering = ['semester', 'code']

ENROLLMENT_KINDS = (
    ('I', 'Instructor'),
    ('A', 'Audit'),
    ('G', 'Graded'),
    )

class Enrollment(models.Model):
    course = models.ForeignKey(Course)
    user = models.ForeignKey(User)
    kind = models.CharField(max_length=1, choices=ENROLLMENT_KINDS)
    notify_on_commit = models.BooleanField(default=True)
    notify_new_grades = models.BooleanField(default=True)

    def __unicode__(self):
        return '%s in %s' % (self.user.username, self.course.tag)

    class Meta:
        unique_together = (("course", "user"),)
        ordering = ['course']

    def is_instructor(self):
        return self.kind == 'I'

    def is_student(self):
        return self.kind != 'I'

    def is_graded(self):
        return self.kind == 'G'

    def is_auditing(self):
        return self.kind == 'A'

LINK_KINDS = (
    ('H', 'Home'),
    ('R', 'Repository'),
    ('C', 'Calendar'),
    ('T', 'Text'),
    ('F', 'Feed'),
    ('O', 'Other'),
    )

class CourseLink(models.Model):
    course = models.ForeignKey(Course)
    kind = models.CharField(max_length=1, choices=LINK_KINDS)
    url = models.URLField(verify_exists=False)

    def __unicode__(self):
        return '%s %s %s' % (self.course.tag, self.kind,
                             self.get_abbrev_url())

    def get_abbrev_url(self):
        scheme, host, path, q, frag = urlsplit(self.url)
        if len(path) > 20:
            path = path[:20]+u'…'
        return host+path

python/l3ms/courses/forms.py
from datetime import date
from django import forms
from models import Enrollment
from strings import *

class EnrollmentForm(forms.Form):
    key = forms.CharField(label=LABEL_KEY, max_length=32)
    for_credit = forms.BooleanField(label=LABEL_FOR_CREDIT, required=False)

    def __init__(self, user, course, *args, **kwargs):
        self.user = user
        self.course = course
        # Assume for_credit, unless this semester is over
        initial = {'for_credit':
                       date.today() < course.semester.end_date}
        super(EnrollmentForm, self).__init__(*args, initial=initial, **kwargs)
# 2fdc422

    def clean_key(self):
        key = self.cleaned_data['key']
        if key != self.course.key:
            raise forms.ValidationError(M_INCORRECT_KEY)
        return key

    def save(self, commit=True):
        e = Enrollment(course=self.course, user=self.user,
                       kind='G' if self.cleaned_data['for_credit'] else 'A')
        self.user.groups.add(self.course.group) # does this save?
        if commit:
            e.save()
        return e

class CourseOptionsForm(forms.ModelForm):
    class Meta:
        model = Enrollment
        exclude = ['course', 'user', 'kind']

python/l3ms/courses/views.py
from django.conf import settings
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from l3ms.http_auth.views import login_required, SESSION_MESSAGE
from l3ms.utils import except404
from models import Course, Enrollment
from strings import *
from templatetags.enrollment import enrolled_in
import forms
import re

def all_courses(request):
    return render_to_response('courses/all.html',
                              {'user': request.user,
                               'site_name': settings.SITE_NAME,
                               'courses': Course.objects.all()})

def enroll(request, course):
    assert request.user.is_authenticated()
    assert not enrolled_in(request.user, course.tag)
    if request.method == 'POST':
        form = forms.EnrollmentForm(request.user, course, request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.get_full_path())
    else:
        form = forms.EnrollmentForm(request.user, course)
    return render_to_response('courses/enroll.html',
                              {'user': request.user,
                               'course': course,
                               'site_name': settings.SITE_NAME,
                               'form': form,
                               'action': request.get_full_path()})

ONE_COURSE_VIEWS=[]

@login_required
@except404([Course.DoesNotExist])
def one_course(request, tag):
    course = Course.objects.get(pk=tag)

    # Maybe ask for enrollment key instead
    if not enrolled_in(request.user, tag):
        return enroll(request, course)
    enrollment = Enrollment.objects.get(user=request.user, course=course)

    # Course page has a preferences section, handled by this POST.
    if request.method == 'POST':
        form = forms.CourseOptionsForm(request.POST, instance=enrollment)
        if form.is_valid():
            form.save()
            request.session[SESSION_MESSAGE] = M_PREFS_SAVED
            return HttpResponseRedirect(request.get_full_path())
    else:
        form = forms.CourseOptionsForm(instance=enrollment)

    # Not a POST or form not valid, so display page as normal.

    # Session message
    message = request.session.get(SESSION_MESSAGE, '')
    if message:
        del request.session[SESSION_MESSAGE]

    # Allow other functions in ONE_COURSE_VIEWS to augment context.
    context = {'user': request.user,
               'site_name': settings.SITE_NAME,
               'course': course,
               'enrollment': enrollment,
               'form': form,
               'action': request.get_full_path(),
               'message': message}

    for view in ONE_COURSE_VIEWS:
        view(request, context)

    return render_to_response('courses/one.html', context)

@login_required
@except404([Course.DoesNotExist])
def mass_email(request, tag):
    course = Course.objects.get(pk=tag)
    emails = ['%s <%s>' % (e.user.get_full_name(), e.user.email)
              for e in course.get_students()]
    emails = ',\n    '.join(emails)
    return HttpResponse(emails, content_type='text/plain')

def nav(request, path):
    course = None
    message = None
    try:
        course = Course.objects.get(tag__in=re.split(r'[/.]', path))
    except Course.DoesNotExist:
        message = 'DoesNotExist'
    except Course.MultipleObjectsReturned:
        message = 'MultipleObjectsReturned'

    return render_to_response('courses/nav.html',
                              {'user': request.user,
                               'site_name': settings.SITE_NAME,
                               'message': message if settings.DEBUG else '',
                               'course': course})

templates/courses/all.html
{% extends "layout/narrow.html" %}
{% load enrollment %}
{% block small_content %}
<h1>All courses</h1>
{% for c in courses %}
  <div id="allCourses">
    {% ifchanged c.semester %}
    <div class="semester">
      {{ c.semester }}
    </div>
    {% endifchanged %}
    <div class="course {{ user|enrollment_kind:c }}">
      <a href="{% url one_course tag=c.tag %}">{{ c.code }} {{ c.name }}</a>
      ({{ c.get_full_instructor_names|safeseq|join:", "}})
    </div>
  </div>
{% endfor %}


{% endblock %}

templates/courses/enroll.html
{% extends "layout/narrow.html" %}
{% block title %}
  Enroll in {{ course.tag }} | {{ site_name }}
{% endblock %}

{% block small_content %}
<h1>{{course.code}} {{course.name}} ({{ course.semester.name }})</h1>

<p>Instructions</p>

<form class="simpleForm" method="post" action="{{ action }}">
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

{% endblock %}

templates/courses/nav.html
{% load gravatar %}

{% if course %}
<a href="{% url one_course tag=course.tag %}">
  Course
</a>
{% endif %}

{% if message %}
<span><i>{{message}}</i></span>
{% endif %}

{% if user.is_staff %}
<a href="{% url all_users %}">Users</a>
<a href="{% url admin:index %}">Admin</a>
{% endif %}

{% if user.is_authenticated %}
<span>Hello,
  <a href="{% url profile username=user.username %}">
    {{user.username}}
    <img class="gravatar" src="{{user|gravatar:24}}"
         width="24" height="24" />
  </a>
  <a href="{% url auth_logout %}">Log out</a>
</span>
{% else %}
<a href="{% url auth_options %}">Log in or sign up</a>
{% endif %}

templates/courses/one.html
{% extends "layout/base.html" %}
{% load gravatar %}
{% load enrollment %}
{% block title %}
{{course.code}} {{course.semester.name}} | {{site_name}}
{% endblock %}

{% block scripts %}
{{ block.super }}
<script type="text/javascript" src="/l3media/sorttable.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $(".messages").fadeOut(3000)
  $(".sliceWidget").change(function() {
    var sliced = $(this).attr('checked')
    $(".sliceWidget").attr('checked', sliced)
    $(".ifAll").toggleClass("hidden", sliced)
    $(".ifSliced").toggleClass("hidden", !sliced)
    $(".droppable").toggleClass("dropped", sliced)
  })
  $(".expandTool").click(function() {
    var expanded = $(this).hasClass("expanded")
    var id = $(this).attr('id').substr(6)
    if(expanded) {
        $(this).removeClass("expanded").addClass("collapsed")
        $(".descendantOf"+id).addClass("hidden")
        $(".descendantOf"+id+" .expandTool").removeClass("expanded").addClass("collapsed")
    }
    else {
        $(this).removeClass("collapsed").addClass("expanded")
        $(".childOf"+id).removeClass("hidden")
    }
  })
})
</script>
{% endblock %}

{% block content %}
<div id="coursePage">
  <div class="container_12 clearfix">
    <div class="grid_12 alpha omega">
      <h1>{{course.code}}: {{course.name}} • {{course.semester.name}}</h1>
    </div> <!-- grid_12 -->
  </div>   <!-- container_12 -->

  <div class="container_12 clearfix">
    <div class="grid_2 alpha">
      <h2>Roster</h2>
      {{ course.get_instructors|roster_list:"instructorList" }}
      {% if enrollment.is_student %}
      {{ course.get_graded_students|roster_list:"studentList" }}
      {{ course.get_auditing_students|roster_list:"auditList" }}
      {% else %}
      <p><a href="{% url mass_email tag=course.tag %}">Students' emails</a></p>
      {% endif %}
    </div> <!-- grid_2 -->
    <div class="grid_7">
      <h2>Content</h2>
      <div class="links">
        {% for l in course.courselink_set.all %}
        <a href="{{l.url}}">
          {{ l.get_kind_display }}  → 
          {{ l.get_abbrev_url }}
        {% endfor %}
        </a>
      </div> <!-- links -->

      {% if gradeSummary %}
      <h2 class="break">Assessment</h2>
      {{gradeSummary|safe}}
      {% endif %}
    </div> <!-- grid_7 -->
    <div class="grid_3 omega">
      <h2>Preferences</h2>

      <form method="post" action="{{action}}">
        {{form.as_p}}
        <input type="submit" value="Save" />
        <p><span class="messages">{{ message }}</span>&nbsp;</p>
      </form>
    </div> <!-- grid_3 -->

    {% if enrollment.is_instructor %}
    <div class="grid_12 alpha omega">
      {% if gradeSheet %}
        {{gradeSheet|safe}}
      {% else %}
        {{course.get_graded_students|roster_list:"studentList"}}
      {% endif %}
      {{course.get_auditing_students|roster_list:"auditList"}}
    </div> <!-- grid_12 -->
    {% endif %}
  </div>   <!-- container_12 -->
</div>     <!-- coursePage -->
{% endblock %}

templates/courses/roster.html
{% load gravatar %}
<ul id="{{id}}" class="roster">
  {% for u in users %}
  <li>
    <a href="{% url profile username=u.username %}"
       title="{{ u.get_full_name }}">
      <img class="gravatar" src="{{ u|gravatar:size }}"
           width="{{size}}" height="{{size}}" />
      {{ u.username }}
    </a>
  </li>
  {% endfor %}
</ul>